version: 2.1

executors:
  self-hosted-executor:
    docker:
      - image: circleci/node:16  # Pre-installed Node.js and npm
    resource_class: medium

jobs:
  test:
    executor: self-hosted-executor
    parallelism: 3  # Run this job in parallel across two containers
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            npm install
            npm install --save-dev jest-junit  # Ensure jest-junit is installed
      - run:
          name: "Run Tests and Generate Results"
          command: |
            mkdir -p test-results
            npx jest --ci --testLocationInResults --runInBand --coverage
      - run:
          name: "Check Test Results"
          command: ls -l test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  parallel_tests:
    jobs:
      - test
